# Generated by Django 4.2 on 2023-04-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(
                blank=True, max_length=2048, verbose_name="description"
            ),
        ),
    ]
